---
# tasks file for userquota
# - name: Print some debug information 
#   vars: 
#     msg: |
#         Module Variables ("vars"):
#         --------------------------------
#         {{ vars | to_nice_json }} 
 
#         HOST Variables ("hostvars"):
#         --------------------------------
#         {{ hostvars | to_nice_json }} 
#   debug: 
#     msg: "{{ msg.split('\n') }}"       
#   tags: debug_info
  
- name: Log UserQuota event
  debug:
    msg: "UserQuota created: {{ default.quota }}"

# Find all Users and create a ClusterResourceQuota for them
- name: Find all users
  k8s_facts:
    api_version: user.openshift.io/v1
    kind: User
  register:
    users

- name: Create Default ClusterResourceQuota for Non-Excluded Users
  when:
    - users.resources | length > 0
    - exceptions is not defined or item.metadata.name not in exceptions
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/cluster_resource_quota.j2') }}"
  loop: "{{ users.resources }}"
